{
 "title": "Spring Boot Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{status=\"200\"}[30s]) / rate(http_server_requests_seconds_count{status=\"200\"}[30s])"
    }
   ]
  },
  {
   "title": "Pod Uptime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"spring-monitoring\"}) by (pod)"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(system_cpu_usage{job=\"spring-monitoring\"}[30s])"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{container=\"spring-monitoring\"}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=\"200\"}[30s])"
    }
   ]
  }
 ]
}